[build]
  base    = "Client"
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Routes SPA
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# API proxy (évite CORS)
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
  force = true
